version: '2'

services:
  mysql:
    image: mysql
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: koryoukin
      MYSQL_DATABASE: host

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'

  apache2:
    depends_on:
      - mysql
    build: ./apache/
    links:
      - mysql
    ports:
      - '80:80'
    volumes:
      - ./apache/www:/var/www
      - ./apache/conf:/etc/apache2/sites-available/

volumes:
    db_data:
